version: '3'

services:
  app:
    build:
      context: ../Node_Dockerfile
    tty: true
    volumes:
      - ../Node_Dockerfile:/usr/src/app
    networks:
      - my_net
    ports:
      - "3000:3000"
    depends_on:
      - mydb
  mydb:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mydb
    restart: always # se o container para ele vai restartar sozinho 
    tty: true # permite entrar no container de maneira interativa
    volumes:
      - ./storage:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydatabase
#      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=mypassword
    networks:
      - my_net

networks:
  my_net:
    driver: bridge