FROM nginx:latest

RUN apt-get update
RUN apt-get install vim -y

# cria um diretorio dentro do container no / chamado de app
WORKDIR /app
# copia do host para o container
# COPY 

#Diferença entre CMD e ENTRYPOINT